[project]
authors = ["Amahseyn <amahseyn@mhhashemi1379@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "mojo_tensorflow"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
python = ">=3.12.6,<4"
pip = ">=24.2,<25"
numpy = ">=1.26.4,<2"

